package manning.sqlgenerator.service.llm;

/**
 * Contract for large language model clients used to generate SQL prompts.
 */
public interface LanguageModelClient {

  /**
   * @return provider identifier (e.g. {@code "openai"} or {@code "gemini"})
   */
  String getProviderName();

  /**
   * Indicates whether the client is fully configured and ready to serve requests.
   *
   * @return {@code true} if the client can be used, otherwise {@code false}
   */
  boolean isEnabled();

  /**
   * Generates a text response for the supplied prompt.
   *
   * @param prompt prompt to send to the underlying model
   * @return text generated by the provider
   */
  String generateText(String prompt);
}

