CREATE TABLE IF NOT EXISTS "frpm" (
	"CDSCode"	VARCHAR NOT NULL,
	"Academic Year"	VARCHAR,
	"County Code"	VARCHAR,
	"District Code"	INTEGER,
	"School Code"	VARCHAR,
	"County Name"	VARCHAR,
	"District Name"	VARCHAR,
	"School Name"	VARCHAR,
	"District Type"	VARCHAR,
	"School Type"	VARCHAR,
	"Educational Option Type"	VARCHAR,
	"NSLP Provision Status"	VARCHAR,
	"Charter School (Y/N)"	INTEGER,
	"Charter School Number"	VARCHAR,
	"Charter Funding Type"	VARCHAR,
	"IRC"	INTEGER,
	"Low Grade"	VARCHAR,
	"High Grade"	VARCHAR,
	"Enrollment (K-12)"	DOUBLE,
	"Free Meal Count (K-12)"	DOUBLE,
	"Percent (%) Eligible Free (K-12)"	DOUBLE,
	"FRPM Count (K-12)"	DOUBLE,
	"Percent (%) Eligible FRPM (K-12)"	DOUBLE,
	"Enrollment (Ages 5-17)"	DOUBLE,
	"Free Meal Count (Ages 5-17)"	DOUBLE,
	"Percent (%) Eligible Free (Ages 5-17)"	DOUBLE,
	"FRPM Count (Ages 5-17)"	DOUBLE,
	"Percent (%) Eligible FRPM (Ages 5-17)"	DOUBLE,
	"2013-14 CALPADS Fall 1 Certification Status"	INTEGER
	-- ,
	-- FOREIGN KEY("CDSCode") REFERENCES "schools"("CDSCode"),
	-- PRIMARY KEY("CDSCode")
);

CREATE TABLE IF NOT EXISTS "satscores" (
	"cds"	VARCHAR NOT NULL,
	"rtype"	VARCHAR NOT NULL,
	"sname"	VARCHAR,
	"dname"	VARCHAR,
	"cname"	VARCHAR,
	"enroll12"	INTEGER NOT NULL,
	"NumTstTakr"	INTEGER NOT NULL,
	"AvgScrRead"	INTEGER,
	"AvgScrMath"	INTEGER,
	"AvgScrWrite"	INTEGER,
	"NumGE1500"	INTEGER
	-- ,
	-- FOREIGN KEY("cds") REFERENCES "schools"("CDSCode"),
	-- PRIMARY KEY("cds")
);
CREATE TABLE IF NOT EXISTS "schools" (
	"CDSCode"	VARCHAR NOT NULL,
	"NCESDist"	VARCHAR,
	"NCESSchool"	VARCHAR,
	"StatusType"	VARCHAR NOT NULL,
	"County"	VARCHAR NOT NULL,
	"District"	VARCHAR NOT NULL,
	"School"	VARCHAR,
	"Street"	VARCHAR,
	"StreetAbr"	VARCHAR,
	"City"	VARCHAR,
	"Zip"	VARCHAR,
	"State"	VARCHAR,
	"MailStreet"	VARCHAR,
	"MailStrAbr"	VARCHAR,
	"MailCity"	VARCHAR,
	"MailZip"	VARCHAR,
	"MailState"	VARCHAR,
	"Phone"	VARCHAR,
	"Ext"	VARCHAR,
	"Website"	VARCHAR,
	"OpenDate"	DATE,
	"ClosedDate"	DATE,
	"Charter"	INTEGER,
	"CharterNum"	VARCHAR,
	"FundingType"	VARCHAR,
	"DOC"	VARCHAR NOT NULL,
	"DOCType"	VARCHAR NOT NULL,
	"SOC"	VARCHAR,
	"SOCType"	VARCHAR,
	"EdOpsCode"	VARCHAR,
	"EdOpsName"	VARCHAR,
	"EILCode"	VARCHAR,
	"EILName"	VARCHAR,
	"GSoffered"	VARCHAR,
	"GSserved"	VARCHAR,
	"Virtual"	VARCHAR,
	"Magnet"	INTEGER,
	"Latitude"	DOUBLE,
	"Longitude"	DOUBLE,
	"AdmFName1"	VARCHAR,
	"AdmLName1"	VARCHAR,
	"AdmEmail1"	VARCHAR,
	"AdmFName2"	VARCHAR,
	"AdmLName2"	VARCHAR,
	"AdmEmail2"	VARCHAR,
	"AdmFName3"	VARCHAR,
	"AdmLName3"	VARCHAR,
	"AdmEmail3"	VARCHAR,
	"LastUpdate"	DATE NOT NULL
  -- ,
	-- PRIMARY KEY("CDSCode")
);
